# Indexing 

Indexing means accessing a single element using its position.

### Positive Indexing

In [1]:
import numpy as n

In [2]:
a = n.array([10,20,30,40,50])


In [3]:
print(a)

[10 20 30 40 50]


In [10]:
print(a.ndim)

1


In [5]:
a[4]

50

In [6]:
a[0]

10

In [7]:
a[3]

40

In [8]:
print(a[2])

30


In [9]:
print(a[9])

IndexError: index 9 is out of bounds for axis 0 with size 5

In [11]:
b = n.array([[11,22,33,44,55],[66,77,88,99,110]])

In [12]:
print(b)

[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]


In [13]:
print(b.ndim)

2


In [14]:
print(b.shape)

(2, 5)


In [15]:
print(b.size)

10


#### **Syntax 2-D array indexing :- arr[row][column]      or arr[row,column]**

In [16]:
b[0][2]

33

In [18]:
b[0,2]

33

In [19]:
print(b[1][3])

99


In [20]:
b[1,4]

110

### Negative Indexing

Negative indexing starts from the end

In [21]:
a

array([10, 20, 30, 40, 50])

In [22]:
b

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 110]])

In [23]:
a[-3]

30

In [24]:
a[-5]

10

In [25]:
a[0]

10

In [26]:
a[-2]

40

In [27]:
b[0][4]

55

In [28]:
b[0,4]

55

In [29]:
b[-1,-1]

110

In [30]:
b

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 110]])

In [31]:
b[-1,-3]

88

In [33]:
b[-2,-4]

22

### Boolean Indexing

used for filtering data using condition

In [34]:
a

array([10, 20, 30, 40, 50])

##### Filter Value

In [35]:
print(a>25)

[False False  True  True  True]


In [38]:
print(a > 10)

[False  True  True  True  True]


In [39]:
print(a >= 10)

[ True  True  True  True  True]


In [40]:
print(a<10)

[False False False False False]


In [43]:
even = a[a%2 == 0]
print(even)

[10 20 30 40 50]


In [44]:
even = a%2 == 0
print(even)

[ True  True  True  True  True]


### Fancy Indexing 

Access using list of index fancy indexing means using list of index.

In [45]:
x = n.array([31,41,51,61,71,81])
print(x)

[31 41 51 61 71 81]


In [46]:
x[2]

51

In [47]:
print(x[[4,3,0,1]])

[71 61 31 41]


In [48]:
print(x[4,3,0,1])

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [49]:
print(x[[3,0,2]])

[61 31 51]


In [57]:
y = n.array([[3,6,9,12,15],
            [18,21,24,27,30],
            [33,36,39,42,45]])
print(y)

[[ 3  6  9 12 15]
 [18 21 24 27 30]
 [33 36 39 42 45]]


In [58]:
print(y[[0,1]])

[[ 3  6  9 12 15]
 [18 21 24 27 30]]


In [60]:
print(y[[0,2]])

[[ 3  6  9 12 15]
 [33 36 39 42 45]]


In [63]:
print(y[:,[0,2]])

[[ 3  9]
 [18 24]
 [33 39]]


In [64]:
print(y[:,[3,4]])

[[12 15]
 [27 30]
 [42 45]]


In [69]:
y

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45]])

In [70]:
print(y[[0, 1, 2], [2, 1, 0]])

[ 9 21 33]


# Slicing

Slicing means gettting a range of elements

**Syntax :-  arr[start : end : step]**

In [71]:
a

array([10, 20, 30, 40, 50])

In [73]:
print(a[0:3])

[10 20 30]


In [74]:
print(a[0:5:1])

[10 20 30 40 50]


In [75]:
print(a[2:5:1])

[30 40 50]


In [76]:
a[0:5:2]

array([10, 30, 50])

In [82]:
print(a[4:0:-1])

[50 40 30 20]


In [83]:
a[::-1]

array([50, 40, 30, 20, 10])